### PR TITLE
Help Update

### PR DESCRIPTION
**Pull request by KanadeDev**
### What has changed?
- Added /help [page and command].
- A new command description has been added.
- Added a new ReadME.

### CODE REVIEW

**Comment by hvlxh** [comment]
nice

**Comment by KanadeDev** [comment]
> nice

?

**Comment by KanadeDev** [comment]
Closed due to WaxNex not liking me or somthing

**Comment by vp817** [comment]
are u braindead? I didnt merge cuz i was going to push the lastest version some time cuz of some calculations in js i need to do some things so it will be delayed or tmr

**Comment by vp817** [comment]
that is how i normally speak

**Comment by KanadeDev** [comment]
....

**Comment by KanadeDev** [comment]
Old

**Pull request closed without merging**
