### PR TITLE
Update HelpCMD.js

### PR DESCRIPTION
**Pull request by AnyBananaGAME**
`}` was placed in a wrong position

### CODE REVIEW

**Comment by vp817** [comment]
no u r wrong what u r doing is a loop in a loop

**Comment by AnyBananaGAME** [comment]
> no u r wrong what u r doing is a loop in a loop

it crashes if its there? "command" not defined

**Comment by AnyBananaGAME** [comment]
it crashed tho?

**Comment by AnyBananaGAME** [comment]
did not mean to click close...

**Comment by AnyBananaGAME** [comment]
`
                command.aliases.forEach(prefix => {
                ^

ReferenceError: command is not defined
`

**Comment by AnyBananaGAME** [comment]
works fine too

**Comment by AnyBananaGAME** [comment]
```js
help
[Server|Info|52:15:17] > ----- Help -----
[Server|Info|52:15:17] > /gamemode: change ur gamemode
[Server|Info|52:15:17] > /gm: change ur gamemode
[Server|Info|52:15:17] > /gamemode: change ur gamemode
[Server|Info|52:15:17] > /gm: change ur gamemode
[Server|Info|52:15:17] > /help: help command
[Server|Info|52:15:17] > /?: help command
[Server|Info|52:15:17] > /gamemode: change ur gamemode
[Server|Info|52:15:17] > /gm: change ur gamemode
[Server|Info|52:15:17] > /help: help command
[Server|Info|52:15:17] > /?: help command
[Server|Info|52:15:17] > /list: show a list of the online players
[Server|Info|52:15:17] > /gamemode: change ur gamemode
[Server|Info|52:15:17] > /gm: change ur gamemode
[Server|Info|52:15:17] > /help: help command
[Server|Info|52:15:17] > /?: help command
[Server|Info|52:15:17] > /list: show a list of the online players
[Server|Info|52:15:17] > /stop: stop command
[Server|Info|52:15:17] > /gamemode: change ur gamemode
[Server|Info|52:15:17] > /gm: change ur gamemode
[Server|Info|52:15:17] > /help: help command
[Server|Info|52:15:17] > /?: help command
[Server|Info|52:15:17] > /list: show a list of the online players
[Server|Info|52:15:17] > /stop: stop command
[Server|Info|52:15:17] > /version: Shows the version of BBMC is running or plugin version.
[Server|Info|52:15:17] > /about: Shows the version of BBMC is running or plugin version.
[Server|Info|52:15:17] > /ver: Shows the version of BBMC is running or plugin version.
[Server|Info|52:15:17] > /versions: Shows the version of BBMC is running or plugin version.
```

**Comment by AnyBananaGAME** [comment]
oh i c

**Pull request closed without merging**
